db=DB()
db('Formularios').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Formularios').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Formularios').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Formularios').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Formularios').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Post-de-Formulario').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Post-de-Formulario').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Post-de-Formulario').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Post-de-Formulario').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Post-de-Formulario').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Opciones').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Opciones').campo('Valores',db.list,False,True,False,False,0,-1,None,None)
db('Formularios').insertar('Contacto', [[ {'Nombre': 'text', 'name': 'titulo', 'value': ''},{'Email': 'email', 'name': 'email', 'value': ''},{'Contenido': 'text', 'name': 'contenido', 'value': ''} ]], {'Formulario': 0}, '19/7/2017 16:24:50', [])
db('Post-de-Formulario').insertar('Contacto', [[ {'value': 0, 'name': 'id', 'Formulario': 'hidden-id'},{'Nombre': 'text', 'name': 'titulo', 'value': ''},{'Email': 'email', 'name': 'email', 'value': ''},{'Contenido': 'text', 'name': 'contenido', 'value': ''} ]], {'Post-de-Formulario': 0}, '19/7/2017 16:24:50', [])

db('Opciones').insertar('Antecedentes criminales', ['', 'Misdemeanor', 'Felony'])