# -*- coding: utf-8 -*-
try:
 from modulos.ztec.zdb import DB
except:
 from zdb import DB
db=DB()
db.load=True
db('Galerias').campo('Nombre',db.str,False,True,False,False,0,-1,None,None)
db('Galerias').campo('Contenido',db.list,False,True,False,False,0,-1,None,None)
db('Galerias').campo('args',db.dict,False,True,False,False,0,-1,None,None)
db('Galerias').campo('Fecha',db.str,False,True,False,False,0,-1,None,'%d/%m/%Y %H:%M:%S')
db('Galerias').campo('Status',db.list,False,True,False,False,0,-1,None,None)
db('Galerias').insertar('Arreglos y ramos', [[{'Galeria': 'text', 'name': 'galeria', 'value': 'Arreglos y ramos'}, {'opcion': 0, 'value': 8, 'Imagen 1': 'img-admin', 'name': 'img', 'opciones': 'archivos'}, {'opcion': 0, 'Imagen 2': 'img-admin', 'value': 1, 'name': 'img', 'opciones': 'archivos'}, {'opcion': 0, 'Imagen 3': 'img-admin', 'value': 2, 'name': 'img', 'opciones': 'archivos'}, {'opcion': 0, 'value': 3, 'name': 'img', 'opciones': 'archivos', 'Imagen 4': 'img-admin'}, {'opcion': 0, 'value': 4, 'Imagen 5': 'img-admin', 'opciones': 'archivos', 'name': 'img'}, {'opcion': 0, 'value': 5, 'Imagen 6': 'img-admin', 'opciones': 'archivos', 'name': 'img'}, {'opcion': 0, 'value': 6, 'Imagen 7': 'img-admin', 'name': 'img', 'opciones': 'archivos'}, {'opcion': 0, 'value': 7, 'Imagen 8': 'img-admin', 'name': 'img', 'opciones': 'archivos'}, {'opcion': 0, 'value': 8, 'Imagen 9': 'img-admin', 'name': 'img', 'opciones': 'archivos'}, {'opcion': 0, 'value': 9, 'name': 'img', 'opciones': 'archivos', 'Imagen 10': 'img-admin'}, {'opcion': 0, 'value': 10, 'Imagen 11': 'img-admin', 'opciones': 'archivos', 'name': 'img'}]], {'Galeria': 0}, '1/9/2017 11:46:7', [])
db('Galerias').insertar('Plantas ornamentales', [[{'Galeria': 'text', 'name': 'galeria', 'value': 'Plantas ornamentales'}, {'opcion': 0, 'Imagen 1': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 11}, {'opcion': 0, 'Imagen 2': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 12}, {'Imagen 3': 'img-admin', 'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 13}, {'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 14, 'Imagen 4': 'img-admin'}, {'opcion': 0, 'opciones': 'archivos', 'value': 15, 'Imagen 5': 'img-admin', 'name': 'img'}, {'opcion': 0, 'opciones': 'archivos', 'Imagen 6': 'img-admin', 'value': 16, 'name': 'img'}, {'opcion': 0, 'opciones': 'archivos', 'Imagen 7': 'img-admin', 'name': 'img', 'value': 17}, {'opcion': 0, 'Imagen 8': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 18}, {'opcion': 0, 'Imagen 9': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 19}, {'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 20, 'Imagen 10': 'img-admin'}]], {'Galeria': 1}, '22/6/2017 21:16:14', [])
db('Galerias').insertar('Festejos', [[{'Galeria': 'text', 'name': 'galeria', 'value': 'Festejos'}, {'opcion': 0, 'Imagen 1': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 21}, {'opcion': 0, 'Imagen 2': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 22}, {'Imagen 3': 'img-admin', 'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 23}, {'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 24, 'Imagen 4': 'img-admin'}, {'opcion': 0, 'opciones': 'archivos', 'value': 25, 'Imagen 5': 'img-admin', 'name': 'img'}]], {'Galeria': 2}, '22/6/2017 21:16:14', [])
db('Galerias').insertar('Bodas y bautizos', [[{'Galeria': 'text', 'name': 'galeria', 'value': 'Bodas y bautizos'}, {'opcion': 0, 'Imagen 1': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 26}, {'opcion': 0, 'Imagen 2': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 27}, {'Imagen 3': 'img-admin', 'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 28}, {'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 29, 'Imagen 4': 'img-admin'}, {'opcion': 0, 'opciones': 'archivos', 'value': 30, 'Imagen 5': 'img-admin', 'name': 'img'}, {'opcion': 0, 'opciones': 'archivos', 'Imagen 6': 'img-admin', 'value': 31, 'name': 'img'}, {'opcion': 0, 'opciones': 'archivos', 'Imagen 7': 'img-admin', 'name': 'img', 'value': 32}, {'opcion': 0, 'Imagen 8': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 33}, {'opcion': 0, 'Imagen 9': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 34}, {'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 35, 'Imagen 10': 'img-admin'}, {'opcion': 0, 'opciones': 'archivos', 'value': 36, 'Imagen 11': 'img-admin', 'name': 'img'}]], {'Galeria': 3}, '22/6/2017 21:16:14', [])
db('Galerias').insertar('Hoteles y banquetes', [[{'Galeria': 'text', 'name': 'galeria', 'value': 'Hoteles y banquetes'}, {'opcion': 0, 'Imagen 1': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 37}, {'opcion': 0, 'Imagen 2': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 38}, {'Imagen 3': 'img-admin', 'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 39}, {'opcion': 0, 'opciones': 'archivos', 'name': 'img', 'value': 40, 'Imagen 4': 'img-admin'}, {'opcion': 0, 'opciones': 'archivos', 'value': 41, 'Imagen 5': 'img-admin', 'name': 'img'}, {'opcion': 0, 'opciones': 'archivos', 'Imagen 6': 'img-admin', 'value': 42, 'name': 'img'}, {'opcion': 0, 'opciones': 'archivos', 'Imagen 7': 'img-admin', 'name': 'img', 'value': 43}, {'opcion': 0, 'Imagen 8': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 44}, {'opcion': 0, 'Imagen 9': 'img-admin', 'opciones': 'archivos', 'name': 'img', 'value': 45}]], {'Galeria': 4}, '22/6/2017 21:16:14', [])
db.load=False
