#!/usr/bin/python
# -*- coding: utf-8 -*-
print '''<!DOCTYPE html><html>'''
incluir(data,"head")
print '''<body onload="brython(1)">'''
incluir(data,"widget-navbar")
print '''<section class="container font-s12" style="font-family: sans-serif;">	<div class="row">	<div class="col-md-8">	<article class="text-justify">		<h1>Admision</h1>		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>	</article>	<hr>	<article>		<img src="'''+str(data['base_url'])+'''static/img/undergrad.jpg" class="height-15 alg-top">		<div class="d-inline-block width-50 pad-1 text-justify">			<h2>Graduando</h2>						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>		</div>	</article>			</div>	<aside class="col-md-4">		<img src="'''+str(data['base_url'])+'''static/img/intro_admission.jpg" class="width-100p">		<div class="marg-t2 bg-graylight b-r12 pad-1">			<article>				<h5 class="ubuntu_red">UNEXPO ADMINSION EN UN GLANCE</h5>				Student Enrollment    Undergraduates: 7,032    Graduates: 9,304Class of 2020    43,997 applicants    1,739 matriculated    From 50 states and 76 countriesUndergraduate admission    A holistic review process evaluates academic excellence, intellectual vitality and personal context of each applicant.    Restrictive Early Action application deadline is November 1.    Regular Decision application deadline is January 3.Graduate admission    More than 65 departments and programs offer graduate study.    Business, Law and Medicine have separate admission procedures.    Application deadlines vary by program.Financial Aid    U.S. undergraduates are admitted on a need-blind basis; 100% of need is met for all admitted domestic students.    For undergraduates from households with incomes below $125,000, tuition is fully covered by scholarship and/or grant aid.    Undergraduate parents with incomes below $65,000 are expected to pay nothing toward tuition, room or board.    Nearly 70% of undergraduate students receive assistance toward tuition costs.    Graduate study aid is based on availability of funds and academic merit.    About 85% of graduate students receive financial aid.			</article>			<div class="text-right"><a href="" class="ubuntu_red"> >> Saber mas </a></div>		</div>			</aside>		</div>	</section>'''
incluir(data,"subfooter")
print ''''''
incluir(data,"footer")
print '''</body></html>'''