#!/usr/bin/python
# -*- coding: utf-8 -*-
request_folder="modelos/request/"
models_folder="modelos/"
libs_folder="libs/"
models_dir="modelos"
models_folder=models_dir+"/"
controller_dir="controles"
controller_folder=controller_dir+"/"
http_dir="http"
http_folder=http_dir+"/"
custom_http_dir="custom_http"
custom_http_folder=custom_http_dir+"/"
websocket_dir="websockets"
websocket_folder=websocket_dir+"/"
custom_websocket_dir="custom_websockets"
custom_websocket_folder=custom_websocket_dir+"/"
vistas_dir="vistas"
vistas_folder=vistas_dir+"/"
templates_dir="templates"
templates_folder=templates_dir+"/"
templates_url=vistas_folder+templates_folder
widgets_dir="widgets"
widgets_folder=widgets_dir+"/"
js_folder="js/"
widgets_url=vistas_folder+widgets_folder
widgets_js=vistas_folder+widgets_folder+js_folder+""
static_dir="static"
static_folder=static_dir+"/"
js_url=static_folder+js_folder
plugins_dir="plugins"
plugins_folder=plugins_dir+"/"
widgets_dir="widgets"
widgets_folder=widgets_dir+"/"
php_dir="php"
php_folder=php_dir+"/"
traducciones_folder="traducciones/"


